<a href="https://colab.research.google.com/github/piyush1856/maths-for-machine-learning/blob/main/_01_iit_roorkee_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# defining a vector
v = np.array([1, -1, 2])
w = np.array([2, 5, 2])

In [5]:
# addition
print(v + w)

[3 4 4]


In [6]:
# Substaction
print(v - w)

[-1 -6  0]


In [7]:
# Scaler Multiplication
print(3 * v)

[ 3 -3  6]


In [9]:
# length / magnitude of v vector
print(np.linalg.norm(v))

2.449489742783178


In [10]:
# dot product
np.dot(v, w)

1