<a href="https://colab.research.google.com/github/piyush1856/maths-for-machine-learning/blob/main/_02_iit_roorkee_matrix_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
p = np.array([[1,7], [2,1], [3,2]])
p

array([[1, 7],
       [2, 1],
       [3, 2]])

In [6]:
q = np.array([[1,1], [1,-1], [1,0]])
q

array([[ 1,  1],
       [ 1, -1],
       [ 1,  0]])

In [7]:
# addition of matrix
c = np.add(p, q)
c

array([[2, 8],
       [3, 0],
       [4, 2]])

In [9]:
# substraction of matrix
s = np.subtract(p,q)
s

array([[0, 6],
       [1, 2],
       [2, 2]])

In [11]:
r = np.array([[1,3,1], [1,0,1]])
r

array([[1, 3, 1],
       [1, 0, 1]])

In [13]:
# multiplication
m = np.dot(p, r)
m

array([[8, 3, 8],
       [3, 6, 3],
       [5, 9, 5]])

In [15]:
# determinant
det = np.linalg.det(m)
det

0.0

- Since determinant is zero, it is singular matrix
- no inverse possible, will get error

In [16]:
np.linalg.inv(m)

LinAlgError: Singular matrix

In [18]:
m = np.array([[1, -1], [2,3]])
inv = np.linalg.inv(m)
inv

array([[ 0.6,  0.2],
       [-0.4,  0.2]])